---
- name: Setup Jenkins and Docker
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Force remove old Jenkins repo list
      file:
        path: /etc/apt/sources.list.d/jenkins.list
        state: absent

    - name: Install Java
      apt:
        name: openjdk-17-jre
        update_cache: yes
        state: present

    - name: Download Jenkins Key to Global Trusted Folder
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /etc/apt/trusted.gpg.d/jenkins.asc
        force: yes

    - name: Add Jenkins Repo
      apt_repository:
        repo: "deb https://pkg.jenkins.io/debian-stable binary/"
        state: present
        update_cache: yes

    - name: Install Jenkins and Docker
      apt:
        pkg:
          - jenkins
          - docker.io
        update_cache: yes
        state: present

    - name: Start Jenkins Service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes