---
- name: Setup Jenkins and Docker
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Nuke all old Jenkins lists to stop cache errors
      shell: rm -f /etc/apt/sources.list.d/jenkins*.list /etc/apt/sources.list.d/archive_uri*.list
      warn: false

    - name: Install Java
      apt:
        name: openjdk-17-jre
        update_cache: yes
        state: present

    - name: Add Jenkins Repo with Trusted Bypass
      shell: echo "deb [trusted=yes] https://pkg.jenkins.io/debian-stable binary/" > /etc/apt/sources.list.d/jenkins.list

    - name: Install Jenkins and Docker
      apt:
        pkg:
          - jenkins
          - docker.io
        update_cache: yes
        state: present

    - name: Start Jenkins Service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes